CREATE TABLE "GCG_5971_IAM_Pen_RPT"(
 "BIRUNID" BIGINT,
 "EMPLOYEE" CHAR(6),
 "LAST_NAME" CHAR(15),
 "FIRST_NAME" CHAR(15),
 "MIDDLE_INITIAL" CHAR(1),
 "SUFFIX" CHAR(4),
 "SSN" CHAR(9),
 "WEEK_1" DOUBLE,
 "WEEK_2" DOUBLE,
 "WEEK_3" DOUBLE,
 "WEEK_4" DOUBLE,
 "WEEK_5" DOUBLE,
 "TOTAL_WEEKS" DOUBLE);